apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/sh", "-c"]
        args: 
          - "echo \"<html><body style='text-align:center; margin-top:50px; background-color:#282c34; color:white;'><h1>Hosted on Kubernetes</h1><h2 style='color:#26748a;'>Responding from Pod: $HOSTNAME</h2><p>Created by Pietro Rusconi</p></body></html>\" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80